dubbo:
  application:
    name: dubbo-goods
  scan:
    base-packages: cn.edu.xmu.oomall.service
  registry:
    address: nacos://localhost:8848
  protocol:
    name: dubbo
    port: 19200

spring:
  cloud:
    nacos:
      server-addr: localhost:8848
server:
  port: 9200